export const TUTOR_BOARD_OPTIONS = [
  "CBSE",
  "ICSE",
  "ISC",
  "IGCSE",
  "IB MYP",
  "IB DP",
  "JEE Main",
  "JEE Advanced",
  "Maths Olympiad",
];

export const TUTOR_CLASS_OPTIONS = [
  "Class 1",
  "Class 2",
  "Class 3",
  "Class 4",
  "Class 5",
  "Class 6",
  "Class 7",
  "Class 8",
  "Class 9",
  "Class 10",
  "Class 11",
  "Class 12",
  "IB MYP 1",
  "IB MYP 2",
  "IB MYP 3",
  "IB MYP 4",
  "IB MYP 5",
  "IB DP AA SL",
  "IB DP AA HL",
  "IB DP AI SL",
  "IB DP AI HL",
  "JEE Main",
  "JEE Advanced",
  "Maths Olympiad",
];

export const TUTOR_TOPIC_OPTIONS = [
  "Algebra",
  "Geometry",
  "Trigonometry",
  "Calculus",
  "Statistics",
  "Probability",
  "Coordinate Geometry",
  "Mensuration",
  "Number Systems",
  "Functions",
  "Vectors",
  "Matrices",
  "Reasoning",
  "Olympiad Maths",
];

export const TUTOR_SERVICE_MODE_OPTIONS = [
  "Home Tuition",
  "Online",
  "Hybrid",
  "Crash Course",
  "Doubt Solving",
  "Exam Revision",
];

export const TUTOR_CITY_OPTIONS = ["gurugram", "gurgaon"];

export const TUTOR_LOCALITY_OPTIONS = [
  "Sector 14",
  "Sector 15",
  "Sector 21",
  "Sector 22",
  "Sector 23",
  "Sector 27",
  "Sector 28",
  "Sector 29",
  "Sector 30",
  "Sector 31",
  "Sector 38",
  "Sector 39",
  "Sector 40",
  "Sector 41",
  "Sector 42",
  "Sector 43",
  "Sector 44",
  "Sector 45",
  "Sector 46",
  "Sector 47",
  "Sector 48",
  "Sector 49",
  "Sector 50",
  "Sector 51",
  "Sector 52",
  "Sector 53",
  "Sector 54",
  "Sector 55",
  "Sector 56",
  "Sector 57",
  "Sector 58",
  "Sector 59",
  "Sector 60",
  "Sector 61",
  "Sector 62",
  "Sector 63",
  "Sector 65",
  "Sector 66",
  "Sector 67",
  "Sector 68",
  "Sector 69",
  "Sector 70",
  "Sector 71",
  "Sector 72",
  "Sector 74",
  "Sector 75",
  "Sector 76",
  "Sector 77",
  "Sector 78",
  "Sector 79",
  "Sector 80",
  "DLF Phase 1",
  "DLF Phase 2",
  "DLF Phase 3",
  "DLF Phase 4",
  "DLF Phase 5",
  "Golf Course Road",
  "Golf Course Extension Road",
  "Sohna Road",
  "South City 1",
  "South City 2",
  "Sushant Lok 1",
  "Sushant Lok 2",
];

export const TUTOR_STATUS_OPTIONS = ["active", "inactive"];

export const BLOG_CATEGORY_OPTIONS = [
  "Maths Planning",
  "CBSE Maths",
  "ICSE / ISC Maths",
  "IGCSE Maths",
  "IB Maths",
  "IB DP Maths",
  "JEE Maths",
  "Parents Guide",
];

export const BLOG_STATUS_OPTIONS = ["draft", "published", "scheduled"];

export const RESULT_BOARD_OPTIONS = [
  "CBSE",
  "ICSE",
  "ISC",
  "IGCSE",
  "IB",
  "IB Diploma",
  "JEE Main",
  "JEE Advanced",
  "Foundation Maths",
];

export const RESULT_CLASS_LEVEL_OPTIONS = [
  "Class 6",
  "Class 7",
  "Class 8",
  "Class 9",
  "Class 10",
  "Class 11",
  "Class 12",
  "IGCSE Core",
  "IGCSE Extended",
  "IB MYP",
  "IB DP",
  "AA HL",
  "AA SL",
  "AI HL",
  "AI SL",
  "JEE Main",
  "JEE Advanced",
];

export const RESULT_STATUS_OPTIONS = ["draft", "approved"];

export const PAGE_TYPE_OPTIONS = ["board", "subject"];

export const PAGE_STATUS_OPTIONS = ["draft", "published", "archived"];
